<?php
/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class FVTilmelding {
	private $fv_tilmelding_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'fv_tilmelding_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'fv_tilmelding_page_init' ) );
	}

	public function fv_tilmelding_add_plugin_page() {
		add_menu_page(
			'FV Tilmelding', // page_title
			'FV Tilmelding', // menu_title
			'manage_options', // capability
			'fv-tilmelding', // menu_slug
			array( $this, 'fv_tilmelding_create_admin_page' ), // function
			'dashicons-admin-generic', // icon_url
			65 // position
		);
	}

	public function fv_tilmelding_create_admin_page() {
		$this->fv_tilmelding_options = get_option( 'fv_tilmelding_option_name' ); ?>

		<div class="wrap">
			<h2>FV Tilmelding</h2>
			<p>FV Tilmelding</p>
			<?php settings_errors(); ?>

			<form method="post" action="options.php">
				<?php
					settings_fields( 'fv_tilmelding_option_group' );
					do_settings_sections( 'fv-tilmelding-admin' );
					submit_button();
				?>
			</form>
		</div>
	<?php }

	public function fv_tilmelding_page_init() {
		register_setting(
			'fv_tilmelding_option_group', // option_group
			'fv_tilmelding_option_name', // option_name
			array( $this, 'fv_tilmelding_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'fv_tilmelding_setting_section', // id
			'Settings', // title
			array( $this, 'fv_tilmelding_section_info' ), // callback
			'fv-tilmelding-admin' // page
		);

		add_settings_field(
			'url_0', // id
			'url', // title
			array( $this, 'url_0_callback' ), // callback
			'fv-tilmelding-admin', // page
			'fv_tilmelding_setting_section' // section
		);
	}

	public function fv_tilmelding_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['url_0'] ) ) {
			$sanitary_values['url_0'] = sanitize_text_field( $input['url_0'] );
		}

		return $sanitary_values;
	}

	public function fv_tilmelding_section_info() {
		
	}

	public function url_0_callback() {
		printf(
			'<input class="regular-text" type="text" name="fv_tilmelding_option_name[url_0]" id="url_0" value="%s">',
			isset( $this->fv_tilmelding_options['url_0'] ) ? esc_attr( $this->fv_tilmelding_options['url_0']) : ''
		);
	}

}
if ( is_admin() )
	$fv_tilmelding = new FVTilmelding();

/* 
 * Retrieve this value with:
 * $fv_tilmelding_options = get_option( 'fv_tilmelding_option_name' ); // Array of All Options
 * $url_0 = $fv_tilmelding_options['url_0']; // url
 */
